import { ExternalLink } from "lucide-react";

export function DemoBanner() {
  return (
    <div className="flex items-center justify-center gap-3 border-b border-amber-500/20 bg-amber-500/10 px-4 py-2 text-sm text-amber-200">
      <span className="font-medium">
        Live demo — data is synthetic, generated by AI agents watching a fictional company.
      </span>
      <a
        href="https://github.com/serpin-taxt/openchief"
        target="_blank"
        rel="noopener noreferrer"
        className="inline-flex items-center gap-1 rounded-md bg-amber-500/20 px-2 py-0.5 text-amber-100 transition hover:bg-amber-500/30"
      >
        Deploy your own
        <ExternalLink className="h-3 w-3" />
      </a>
    </div>
  );
}
